baseURL = "https://aakatev.github.io/bigbluebutton-js-docs/"
title = "BigBlueButton JavaScript"
enableRobotsTXT = true
themesDir = "../.."
theme = "compose"
enableGitInfo = true
publishDir = "../docs"

disableKinds = ["taxonomy", "taxonomyTerm"]

#  menu items
[[menu.main]]
    name = "Docs"
    weight = 2
    url = "docs/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

# Everything below this are Site Params

[params]
  author = "bigbluebutton-js"
  searchPlaceholder = "Search the docs ..."
  repo = "https://github.com/aakatev/bigbluebutton-js"

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  [params.logo]
    lightMode = "logo.png"
    darkMode = "logo.png"

  [params.source]
    name = "GitHub"
    icon = "github.svg"
    url = "https://github.com/aakatev/bigbluebutton-js"
